[build]
command = "npm run build"
publish = "dist/projeto-rpg"

[[redirects]]
from = "/api/*"
to = "https://sistemarpg-production.up.railway.app/:splat"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
